services:
  nextjs:
    container_name: nextjs-app
    build: ./front
    restart: always
    volumes:
      - .:/front/app
    ports:
      - "3000:3000"
    env_file:
      - ./front/.env
